### ISSUE TITLE
Error saving metrics

### ISSUE THREAD

**Issue by bborysenko** [mbogus/kube-amqp-autoscale#4]
Could you please advice what can be wrong:

```
Error saving metrics: parse 'amqp://guest:guest@xx.xx.xx.xx:5673//': first path segment in URL cannot contain colon
Not enough metrics to calculate new size, required at least 0.75 was 0.00 metrics ratio
```

**Comment by bborysenko** [comment]
something similar https://github.com/streadway/amqp/issues/303

**Comment by vdoodala** [comment]
Is this issue still open?? I am facing the same one.

Failed to get queue length for queue <name>: parse 'amqp://username:pasowrd@xxxhost_namexxx:5672//': first path segment in URL cannot contain colon

**Comment by fresnault** [comment]
Yep this issue is still open...

Failed to get queue length for queue mapping: parse 'amqp://guest:guest@rabbitmq:5672//': first path segment in URL cannot contain colon

Failed to get queue length for queue mapping: parse 'amqp://guest:guest@XX.XXX.XX.XX:5672//': first path segment in URL cannot contain colon

Impossible to run the project.

**Comment by fresnault** [comment]
@mbogus it seems that you have corrected the error `first path segment in the URL can not contain colon` in your last commit.
Now I have the following error:  `host must be a URL or a host:port pair: "'https://127.0.0.1:443'"` (with this docker image https://hub.docker.com/r/mbogus/kube-amqp-autoscale/builds/bbgrn6tsfeewytzieundwnn/)

I am interested in your project if you ever need help.

**Comment by mbogus** [comment]
Issues with quoted URLs for both AMQP and API have been addressed now
